server:
  servlet:
    context-path: /api/identity-service
  port: ${SERVER_PORT:9080}

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${IDENTITY_DB_NAME:identity-service}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_USER_PW:123456}
  jpa:
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: ${ENABLED_LIQUIBASE:true}
  security:
    oauth2:
      client:
        registration:
          # registering keycloak as oauth2 client with spring security
          keycloak:
            client-id: ${application.keycloak.resource}
            client-secret: ${application.keycloak.credentials-secret}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE:authorization_code}
            scope:
              - openid
              - offline_access
              - profile
        provider:
          keycloak:
            issuer-uri: ${application.keycloak.auth-server-url}/realms/${application.keycloak.realm}
            user-name-attribute: preferred_username
      resourceserver:
        # provide keycloak as issuer provider to verify jwt signature
        jwt:
          issuer-uri: ${application.keycloak.auth-server-url}/realms/${application.keycloak.realm}
          jwk-set-uri: ${application.keycloak.auth-server-url}/realms/${application.keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    com.preschool: ${APPLICATION_LOG_LEVEL:DEBUG}

# Actuator and Prometheus configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s,2s,5s,10s

application:
  sensitive:
    fields: ${SENSITIVE_FIELDS:password,pwd}
    hide-type: ${HIDE_TYPE:PARTIAL}
    hide-characters: ${HIDE_CHARACTERS:5}
  jwt:
    secret: ${JWT_SECRET:myVerySecretKeyForJWTToken1234567890}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION:60}
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:7}
    issuer: ${JWT_ISSUER:identity-service}
  keycloak:
    realm: ${KEYCLOAK_REALMS:preschool_be_sit}
    auth-server-url: ${PROTOCOL:http}://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:28080}
    ssl-required: external
    resource: ${KEYCLOAK_CLIENT_ID:preschool_be}
    credentials-secret: ${KEYCLOAK_CLIENT_SECRET:0AWTAhuKRQCxdOhwPANbMi6POfB49Bxm}
  default-kafka:
    server: ${KAFKA_PLAIN_TEXT:http://localhost:29092}
    metrics-topic: ${METRICS_TOPIC:sit.identity-service.metrics-topic}